### ISSUE TITLE
New compression formats

### ISSUE THREAD

**Issue by hugosenari** [fzakaria/nix-http-binary-cache-api-spec#4]
Since Nix 2.4, there are more compression formats.

https://github.com/NixOS/nix/blob/master/src/libstore/binary-cache-store.cc#L167

```cpp
    narInfo->url = "nar/" + narInfo->fileHash->to_string(Base32, false) + ".nar"
        + (compression == "xz"    ? ".xz"   :
           compression == "bzip2" ? ".bz2"  :
           compression == "zstd"  ? ".zst"  :
           compression == "lzip"  ? ".lzip" :
           compression == "lz4"   ? ".lz4"  :
           compression == "br"    ? ".br"   :
           "");
```

**Comment by hugosenari** [comment]
Also I'm not sure if "bzip2" expects a "bzip2" or "bz2" in url path :thinking: 
https://github.com/fzakaria/nix-http-binary-cache-api-spec/blob/main/api.yaml#L142

```yaml
  /nar/{fileHash}.nar.{compression}:
    get:
      parameters:
      - name: compression
        example: bzip2 # or bz2?
        schema:
          type: string
          enum: [xz, bzip2]
```
